### PR TITLE
Remove angular demo

### PR DESCRIPTION
**Pull request by amanji**
The Angular demo uses outdated API concepts and requires regular package updates. In an effort to reduce unnecessary code maintenance, users should consult the official (and more regularly maintained) OrgBook BC implementation for autocomplete and search functionality and referenced StackBlitz examples in the documentation for autofilling forms.

### CODE REVIEW

**Comment by swcurran** [comment]
Is the intention not to have any sample app?  While I agree that having a sophisticated app is not needed, I think it is useful to highlight how to put the auto-complete search widget into a web app.  Is that covered in the docs?  In other words, do we have enough to help a dev add a the widget to their site?

**Comment by wadeking98** [comment]
> Is the intention not to have any sample app? While I agree that having a sophisticated app is not needed, I think it is useful to highlight how to put the auto-complete search widget into a web app. Is that covered in the docs? In other words, do we have enough to help a dev add a the widget to their site?

I believe the documentation for the autocomplete functionality is included here: https://github.com/bcgov/orgbook-api/tree/main/docs#i-want-to-build-a-legal-name-search-component-in-my-application

**Comment by swcurran** [comment]
Sounds good. Perhaps I should have tried to dig in a bit more... :-)

**Review by swcurran — APPROVED** [review]

**Comment by amanji** [comment]
I plan to port this demo to a StackBlitz project and link it in the docs.

**Pull request merged**
